<a href="https://colab.research.google.com/github/Chinmayi-Bachu/Chinmayi-AIML-Course/blob/main/Tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Transpose of Matrix

In [4]:
a = [[10,12,31,24],[22,35,14,38]]
b = np.transpose(a)
print('Original Matrix\n',a)
print('Transpose Matrix\n',b)

Original Matrix
 [[10, 12, 31, 24], [22, 35, 14, 38]]
Transpose Matrix
 [[10 22]
 [12 35]
 [31 14]
 [24 38]]


Transpose of a Matrix (as NumPy array)

In [5]:
a = np.array([[10,12,31,24],[22,35,14,38]])
b=a.T
print('Original Matrix\n',a)
print('Transpose Matrix\n',b)

Original Matrix
 [[10 12 31 24]
 [22 35 14 38]]
Transpose Matrix
 [[10 22]
 [12 35]
 [31 14]
 [24 38]]


Dot Product

In [6]:
a=5
b=4
z=np.dot(a,b)
print(z)

20


Dot product of arrays

In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])
z=np.dot(a,b)
print(z)

32


Matrix Determinant

In [10]:
a = np.random.randint(1,10,[3,3])
det = np.linalg.det(a)
print(int(det))

-83
